# Generated by Django 4.1.5 on 2023-01-03 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeBarbeiro', models.CharField(max_length=50)),
                ('telBarbeiro', models.CharField(max_length=11)),
                ('estaAtivo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Serviço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeServico', models.CharField(max_length=30)),
                ('precoServico', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=50)),
                ('telCliente', models.CharField(max_length=11)),
                ('dataAgendamento', models.DateField()),
                ('horaAgendamento', models.CharField(max_length=20)),
                ('compareceu', models.BooleanField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, max_length=240, null=True)),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.barbeiro')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.serviço')),
            ],
        ),
    ]
